### ISSUE TITLE
Installation Issue with Module

### ISSUE THREAD

**Issue by yashodhank** [viniciusmuniz/whmcs2pushover#2]
Hello,

I have uploaded module file as instructed to modules directory but still I cant able to see Pushover for WHMCS in Addon Modules list in WHMCS Admin area.

I'm using WHMCS 5.3.10 (5.3.10-release.1)

Is this modules still compatible with new version?

Thank you

**Comment by sgrayban** [comment]
I am not seeing the addon listed in WHMCS 6.2.2 either.

**Comment by sgrayban** [comment]
Actually after I looked at your files I saw the install directory should be whmcs2pushover NOT pushover2whmcs as stated in the readme

**Comment by viniciusmuniz** [comment]
Fixed.
